import Card from '@/components/Card'
import Head from 'next/head'
import React from 'react'

const Store = () => {
    return (
        <>
         <Head>
        <title>{"Don't have"}</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
        <h1 className="text-3xl font-bold underline">
            Hello world! Store
            <Card title="Card 1" description="This is the first card." />


        </h1>
        
        </>
        )
}

export default Store